services:

  postgres:
    image: postgres:16-alpine
    container_name: aijob-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: aijob-redis
    restart: unless-stopped

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

    command: redis-server --appendonly yes

  backend:
    build:
      context: ./backend

    container_name: aijob-backend
    restart: unless-stopped

    env_file:
      - .env

    volumes:
      - ./backend:/app

    ports:
      - "8000:8000"

    depends_on:
      postgres:
        condition: service_healthy

      redis:
        condition: service_started

  frontend:
    image: node:22-alpine

    container_name: aijob-frontend

    working_dir: /app

    stdin_open: true
    tty: true

    volumes:
      - ./frontend:/app

    ports:
      - "3000:3000"

    command: sh

volumes:
  postgres_data:
  redis_data:
